### ISSUE TITLE
Inheritance for getters and setters

### ISSUE THREAD

**Issue by alternatebow** [CS111C-META-FALL-2016/LabD-Team1#19]
Um... so just out of curiosity, I noticed that the getters and setters for each 'shape' class are really similar. So that kind of made me wonder why instead of making GraphicShape an interface, we didn't make it a class and just inherit the getters/setters? This would have eliminated the need to implement them.

**Comment by karlnicholas** [comment]
Yes, for sure. They would be, should be, moved down to the base class when the instance variables were moved down (err up) there. Please feel free to do if you have a minute. This is where Eclispe is a big help because it does a lot of these things for you.

**Comment by alternatebow** [comment]
Alright cool. I always remind myself of D.R.Y, so I was curious. I'll get
on it this afternoon.

**Comment by alternatebow** [comment]
Running into some issues, most commonly with null pointer exceptions.

**Comment by alternatebow** [comment]
Still working on converting the GraphicShape into a class, but I am noticing some problems, particularly with the vertices array for each polygon. For some reason the vertix arrays are returning null. I'm not sure why however; the constructors should've filled it with values.

**Comment by karlnicholas** [comment]
The vertix arrays should be left in the individual graphics classes because each they can be handled differently. For example the GraphicsPolygon uses the arrays in the Polygon class as storage and so only constructs temporary method variables, while the other graphics classes store them in the classes instance variables and retrieve them from there. Look closely at line 22 and 22 in GraphicsPolygon and you'll see what I mean. It is different from say lines 26, 27 in the GraphicsCircles class which uses a class variable. Short of it is that

	public int[] getXPoints();
	public int[] getYPoints();
	public void setVertixShape(int i, GraphicShape p);

should not be moved into the GraphicsBaseclass

**Comment by alternatebow** [comment]
I see...  Ok ,I was able to move as many getter methods as I could to the GraphicShape class. I could try to pull request right now, but there's a warning saying it can't automatically merge. Is there some merge conflicts that I have to resolve, or is that something y'all wanna look over first?

**Comment by karlnicholas** [comment]
Naw, that's just me playing with the permissions. I'll start a pull request and see if I can merge them.

Sorry if I'm causing problems with the permissions. Let me know if it's really messing you up and I'll put it back, but I thought it would be more informative if closer to a "real" work environment.

**Comment by alternatebow** [comment]
No it's fine. Gives me a taste of what the real deal could be like.

**Comment by karlnicholas** [comment]
Ouch. There already was an abstract Graphics base class (GraphicsBaseclass), so the code should have been refactored down to there instead of making another abstract base class out of the interface. 

It's better to leave the interface as an interface so that it could be implemented anyway anyone wants, sort of contract between the RecursionProgram/ShapeContainer and any shape that comes along. 

Think about it, and we'll look at it tomorrow.

**Comment by karlnicholas** [comment]
I merged and pushed everything.

**Comment by jillHuang7** [comment]
I saw both the GraphicsBaseclass and GraphicShape class are now abstract. Should we use interface instead?

**Comment by karlnicholas** [comment]
Well, the general idea is that an interface.should be everything a "driver" program needs to do its thing. Like when we had an interface for the lists and the bags in the last project but we implemented them with both arrays and the AList class. In this case we have enough shapes implementing a GraphicsShape that they should all share a common abstract base class, but they shouldn't mess with the interface. It's a common design pattern but something you tend to pick with experience.

**Comment by karlnicholas** [comment]
Anyway, we don't want to "revert back" but instead move those common getters/setters to GraphicsBaseclass.

**Comment by alternatebow** [comment]
But keep graphicsShape an interface right?

**Comment by karlnicholas** [comment]
Yes, "revert back" to graphicsShape as a interface.

**Comment by alternatebow** [comment]
Alright working on it.

**Comment by alternatebow** [comment]
Should ShapeContainer also extrend GraphicsBaseclass, since we're moving commons getters to it as well?

**Comment by karlnicholas** [comment]
No, ShapeContainer  is not a shape. The idea here is simply to move the common methods of *shapes* to GraphicsBaseclass. 

GraphicsBaseclass implements GraphicShape, so there are methods that GraphicShape defines that ShapeContainer wouldn't (or shouldn't) implement since it is not a shape.

**Comment by karlnicholas** [comment]
Looks great.
